server:
  port: 8094

#spring:
#  application:
#    name: API-GATEWAY
#  cloud:
#    gateway:
#      routes:
#        - id: USER-SERVICE
#          uri: lb://USER-SERVICE
#          predicates:
#            - Path=/user/**
#        - id: RATING-SERVICE
#          uri: lb://RATING-SERVICE
#          predicates:
#            - Path=/rating/**
#        - id: HOTEL-SERVICE
#          uri: lb://HOTEL-SERVICE
#          predicates:
#            - Path=/hotel/**,/staff/*

#    or we can use Replacement for all Url -path=/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8071/eureka

